### ISSUE TITLE
General Scrambler 

### ISSUE THREAD

**Issue by Mike968** [PiPinecone/PineCube#10]
A general function / module that will scramble any size "normal" cube

**Comment by PiPinecone** [comment]
In the Cogs folder there is a file called scrambles.py. For whoever starts the command first, you or me, put the code where the comment is and set it equal to the variable used at the end of the chunk.

**Comment by PiPinecone** [comment]
So you did forget to push haha.

**Comment by PiPinecone** [comment]
I'll add it to cogs.

**Comment by PiPinecone** [comment]
I'll work on this. I am going to try to make a function that can have parameters to pass in length and cube size. This will work for a number of puzzles but not all. As they get bigger and into different shapes they gain a number of different moves possible.

**Comment by Mike968** [comment]
Finished. With the new scramble function, new components, moves, and directions can be added for different puzzles
